# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a05bef6cef0c51d4ed0e4dbf88d659fd9066b24cc1ed30c4d57049ff365bf099ff0dbf245f0f70382293f07178380e4925ce15536743a7ea7403d62c6eff2237

test:
  secret_key_base: c5cc949ad5308a7e51529936486226f03dd181181e0341af3a8736db2192a6849fa320dfbeb71f403418295bea5141a1cb3f0ef87da688da170cfe7f476818d4

# Do not keep production secrets in the repository,
# instead read values from the environment.

# FACEBOOK
development:
 secret_key_base: a8d5a5706cf53...
 facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
 facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
test:
 secret_key_base: 432cb5d950462...
 facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
 facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
  
 # GOOGLE
 development:
    google_client_id: <%= ENV["GOOGLE_CLIENT_ID"]
    google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"]
    
 production:
    google_client_id: <%= ENV["GOOGLE_CLIENT_ID"]
    google_client_secret: <%= ENV["GOOGLE_CLIENT_SECRET"]